/**
 * Map merchant/context keywords → category name (matches createDefaultCategories seeds).
 * Returns null if no confident match.
 */
export function inferCategoryName(text: string): string | null {
  const ctx = text.toLowerCase()

  const rules: Array<{ keywords: string[]; category: string }> = [
    {
      keywords: [
        'swiggy',
        'zomato',
        'eatsure',
        'foodpanda',
        'restaurant',
        'cafe',
        'dhaba',
        'hotel food',
        'biryani',
        'pizza',
        'burger',
        'kfc',
        'mcdonald',
        'domino',
        'subway',
        'starbucks',
      ],
      category: 'Dining',
    },
    {
      keywords: [
        'bigbasket',
        'blinkit',
        'grofers',
        'jiomart',
        'dmart',
        'reliance fresh',
        'more supermarket',
        'grocery',
        'vegetables',
        'fruits',
        'kirana',
      ],
      category: 'Groceries',
    },
    {
      keywords: [
        'uber',
        'ola',
        'rapido',
        'metro',
        'irctc',
        'railway',
        'bus ticket',
        'airport',
        'flight',
        'indigo',
        'airindia',
        'spicejet',
        'toll',
        'fuel',
        'petrol',
        'diesel',
      ],
      category: 'Transport',
    },
    {
      keywords: [
        'petrol',
        'diesel',
        'hpcl',
        'bpcl',
        'iocl',
        'indian oil',
        'shell',
        'fuel station',
        'gas station',
      ],
      category: 'Fuel',
    },
    {
      keywords: [
        'amazon',
        'flipkart',
        'myntra',
        'ajio',
        'nykaa',
        'meesho',
        'snapdeal',
        'clothing',
        'apparel',
        'fashion',
        'shoes',
        'shopping mall',
        'retail',
      ],
      category: 'Shopping',
    },
    {
      keywords: [
        'doctor',
        'hospital',
        'clinic',
        'pharmacy',
        'medplus',
        'apollo pharmacy',
        'netmeds',
        '1mg',
        'pharmeasy',
        'diagnostic',
        'lab test',
        'pathology',
        'medicine',
      ],
      category: 'Health',
    },
    {
      keywords: [
        'netflix',
        'hotstar',
        'prime video',
        'spotify',
        'youtube premium',
        'bookmyshow',
        'pvr',
        'inox',
        'cinema',
        'movie',
        'concert',
        'game',
      ],
      category: 'Entertainment',
    },
    {
      keywords: [
        'electricity',
        'bescom',
        'msedcl',
        'tata power',
        'adani electricity',
        'water bill',
        'gas bill',
        'broadband',
        'jio',
        'airtel',
        'bsnl',
        'vi ',
        'vodafone',
        'recharge',
        'mobile bill',
        'wifi',
      ],
      category: 'Utilities',
    },
    {
      keywords: [
        'emi',
        'loan',
        'home loan',
        'car loan',
        'personal loan',
        'credit card bill',
        'credit card payment',
        'iciciprulife',
        'hdfc loan',
      ],
      category: 'EMI',
    },
    {
      keywords: [
        'lic',
        'insurance premium',
        'term plan',
        'health insurance',
        'general insurance',
        'star health',
        'bajaj allianz',
        'icici lombard',
      ],
      category: 'Insurance',
    },
    {
      keywords: [
        'school fee',
        'college fee',
        'tuition',
        'coaching',
        'udemy',
        'coursera',
        'byju',
        'unacademy',
        'books',
        'stationery',
      ],
      category: 'Education',
    },
    {
      keywords: [
        'salon',
        'spa',
        'parlour',
        'parlor',
        'haircut',
        'beauty',
        'grooming',
        'personal care',
      ],
      category: 'Personal Care',
    },
    {
      keywords: ['rent', 'house rent', 'flat rent', 'apartment', 'pg rent', 'hostel rent'],
      category: 'Rent',
    },
    {
      keywords: [
        'plumber',
        'electrician',
        'carpenter',
        'maid',
        'cook',
        'repair',
        'maintenance',
        'housekeeping',
      ],
      category: 'Household',
    },
    {
      keywords: ['salary', 'payroll', 'monthly pay'],
      category: 'Salary',
    },
    {
      keywords: ['freelance', 'consulting fee', 'contract payment'],
      category: 'Freelance',
    },
    {
      keywords: ['dividend', 'interest credit', 'mutual fund redemption', 'stock sale'],
      category: 'Investment Returns',
    },
  ]

  for (const { keywords, category } of rules) {
    if (keywords.some((kw) => ctx.includes(kw))) return category
  }
  return null
}
